language: python
python:
  - '3.5'
  - '3.6'
install: pip install -r requirements.txt
script: 
  - python setup.py install
  - python dflearn/__init__.py
  - python dflearn/MLtools.py
  - python dflearn/NLtools.py
  - python dflearn/SNPtools.py
